spring:
  profiles:
    active: test


---

server:
  port: 5000

spring:
  profiles: dev
  application:
    name: test-cloud-dev-2.0


---

server:
  port: 8021

spring:
  profiles: test
  application:
    name: test-cloud-test-2.0
