server:
  port: 5000

spring:
  profiles: dev
  application:
    name: client-user-dev


---

server:
  port: 5000
eureka:
  client:
    serviceUrl:
        defaultZone: http://eureka3000.com:3000/eureka
  instance:
    instance-id: user-1 #此实例注册到eureka服务端的唯一的实例ID
    prefer-ip-address: true #是否显示IP地址
    leaseRenewalIntervalInSeconds: 10 #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒 (与下面配置的单位都是秒)
    leaseExpirationDurationInSeconds: 30 #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒

spring:
  application:
    name: client-user #此实例注册到eureka服务端的name
  #分布式链路跟踪
  zipkin:
    base-url: http://localhost:1100  #指定Zipkin server地址
  sleuth:
    sampler:
      probability: 1.0  #request采样的数量 默认是0.1 也即是10%  顾名思义 采取10%的请求数据  因为在分布式系统中，数据量可能会非常大，因此采样非常重要。我们示例数据少最好配置为1全采样


feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
      circuitBreaker:
        requestVolumeThreshold: 5
#        sleepWindowInMilliseconds : 5000   时间

#  threadpool:
#    default:
#      coreSize: 10

#仪表板配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
